name: Build & Deploy

on:
  push:
    branches: [ main ]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  REGISTRY_URL: ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USER  }}/${{ github.event.repository.name }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Log into registry ${{ secrets.REGISTRY }}
      uses: docker/login-action@v1.13.0
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY_URL }}:latest
        # secrets: |
        #   "dotenv=${{ secrets.DOTENV }}"

    - name: Deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
          docker stop ${{ env.REPO_NAME }} || true && docker rm ${{ env.REPO_NAME }} || true
          docker rmi ${{ env.REGISTRY_URL }}:latest
          docker pull ${{ env.REGISTRY_URL }}:latest
          docker run -p 3000:3000 -d -e TOKEN=${{ secrets.TOKEN }} --name ${{ env.REPO_NAME }} ${{ env.REGISTRY_URL }}:latest
